version: '3.8'

services:
  surging.hero.auth:
    image: surgingcloud/surging.hero.auth:${TAG:-latest}
    build:
      context: ../..
      dockerfile: src/Services/Auth/Surging.Hero.AuthHost/Dockerfile.Rider.v2.Debug
      args:
        host_workdir: src/Services/Auth/Surging.Hero.AuthHost
        host_name: Surging.Hero.AuthHost.dll
        sln_name: sln/Surging.Hero.sln
    volumes:
      - ${LOG_DIR:-/var/logs}/auth:/app/logs
    networks:
      - surging_hero_service_net

  surging.hero.basicdata:
    image: surgingcloud/surging.hero.basicdata:${TAG:-latest}
    build:
      context: ../..
      dockerfile: src/Services/BasicData/Surging.Hero.BasicDataHost/Dockerfile.Rider.v2.Debug
      args:
        host_workdir: src/Services/BasicData/Surging.Hero.BasicDataHost
        host_name: Surging.Hero.BasicDataHost.dll
        sln_name: sln/Surging.Hero.sln    
    volumes:
      - ${LOG_DIR:-/var/logs}/basicdata:/app/logs
    networks:
      - surging_hero_service_net

  surging.hero.organization:
    image: surgingcloud/surging.hero.organization:${TAG:-latest}
    build:
      context: ../..
      dockerfile: src/Services/Organization/Surging.Hero.OrganizationHost/Dockerfile.Rider.v2.Debug
      args:
        host_workdir: src/Services/Organization/Surging.Hero.OrganizationHost
        host_name: Surging.Hero.OrganizationHost.dll
        sln_name: sln/Surging.Hero.sln      
    volumes:
      - ${LOG_DIR:-/var/logs}/organization:/app/logs
    networks:
      - surging_hero_service_net      

  surging.hero.gateway:
    image: surgingcloud/surging.hero.gateway:${TAG:-latest}
    build:
      context: ../..
      dockerfile: src/Services/Gateway/Surging.Hero.Gateway/Dockerfile.Rider.v2.Debug
      args:
        host_workdir: src/Services/Gateway/Surging.Hero.Gateway
        host_name: Surging.Hero.Gateway.dll
        sln_name: sln/Surging.Hero.sln        
    depends_on:
      - surging.hero.auth
      - surging.hero.basicdata
      - surging.hero.organization
    volumes:
      - ${LOG_DIR:-/var/logs}/gateway:/app/logs
    networks:
      - surging_hero_service_net

  surging.hero.fileservice:
    image: surgingcloud/surging.hero.fileservice:${TAG:-latest}
    build:
      context: ../..
      dockerfile: src/Services/FileService/Surging.Hero.FileService/Dockerfile.Rider.v2.Debug
      args:
        host_workdir: src/Services/FileService/Surging.Hero.FileService
        host_name: Surging.Hero.FileService.dll
        sln_name: sln/Surging.Hero.sln        
    depends_on:
      - surging.hero.basicdata
    volumes:
      - ${LOG_DIR:-/var/logs}/fileservice:/app/logs
    networks:
      - surging_hero_service_net

networks:
  surging_hero_service_net: 
    external:
      name: surging_hero_service_net